/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task.action.issue

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.AbstractCopyTask

class TaskActionIssuePlugin: Plugin<Project> {

    override fun apply(project: Project) {
        project.tasks.withType(AbstractCopyTask::class.java).configureEach { task ->
            task.doFirst {
                println("TaskActionIssuePlugin is running")
            }
        }
    }
}


